### PR TITLE
Compress storage

### PR DESCRIPTION
**Pull request by jroehl**
This PR implements compression/decompression for the stored options using [lz-string](https://www.npmjs.com/package/lz-string) as discussed in #31

### CODE REVIEW

**Comment by jroehl** [comment]
> Thanks for the PR!
> 
> I think default merger/thinner and decompress/compress are always used together, so I think it would make sense to merge the 4 functions into 2: encode/decode (or something like that.
> 
> The logging on line 134 would have to be moved inside the encoder probably.

Thanks for your comments - that definitely made sense... 
I applied your recommendations 👍

**Comment by jroehl** [comment]
@fregante Is there anything left for me to change? Otherwise, it would be great if we could merge the PR sometime.

**Comment by fregante** [comment]
It looks good but I haven't had the time to test it.

**Comment by fregante** [comment]
I published version `1.0.1-1`, perhaps you can try it on `notifier-for-github` and ensure that **no data is lost** there when updating the extension from _non-compressed_ to _compressed_.

**Comment by fregante** [comment]
I tested it on https://github.com/fregante/github-issue-link-status/commit/e8dd62bda8f506ed11ee19d21c915bb8f2785c1f

It seems to work, however in that case it appears to use more space, rather than less (it's just one field though, so not a big deal anyway)

**Comment by fregante** [comment]
News on this?

**Comment by jroehl** [comment]
hi, sorry for being absent for that long - I just tested it with the github-notifier and it works as expected and no data is lost when migrating from uncompressed to compressed data.

**Comment by jroehl** [comment]
Hey, is there anything left to do for me before we can merge this?

**Comment by fregante** [comment]
I'm slightly hesitant to merge this because I'm not sure if it should be released as v2. For the time being you can continue using `webext-options-sync@1.0.1-1` but make sure to save it as `1.0.1-1` in `package.json` and not `^1.0.1-1`

**Comment by jroehl** [comment]
Ok, no worries - I'll go forward using this version! Thanks

**Comment by fregante** [comment]
Since v1, the content stored via `chrome.storage.sync` should not be accessed directly since the defaults are not saved. For this reason, the storage format (in this case "zipped") can be changed without further notice (i.e. it's non-breaking)

**Comment by fregante** [comment]
For a minute I thought that this caused the loss of data in my extension while testing some of its PRs.

Then I realized that this is because once the options are encrypted, you can't use a version older than 1.2.0 to read them; if you do, they're not recognized and therefore read as `{}`

**Comment by jroehl** [comment]
Yep - that's true.. There is no way back 🙈

**Pull request merged**
